#!/usr/bin/env bash
#prints number of lines

echo " --- --- main --- ---"
cloc --by-file --unix --include-ext=go --exclude-dir=apps,sdk .

echo " --- --- apps --- ---"
cloc --by-file --unix --include-ext=go apps

